Repository HorizenOfficial/Sidechains-SDK, pull requests merged in 2023-06, with the labels that each got.

#849 Sdk 1145 - Payload, addresses and proof format
  sdk/src/main/java/io/horizen/sc2sc/CrossChainMessage.java
  sdk/src/main/java/io/horizen/sc2sc/CrossChainMessageSemanticValidator.java
  sdk/src/main/java/io/horizen/sc2sc/CrossChainMessageSerializer.java
  sdk/src/main/java/io/horizen/sc2sc/CrossChainRedeemMessageImpl.java
  sdk/src/main/java/io/horizen/sc2sc/CrossChainRedeemMessageSemanticValidator.java
  sdk/src/main/scala/io/horizen/account/sc2sc/AbstractCrossChainMessageProcessor.scala
  sdk/src/main/scala/io/horizen/account/sc2sc/AccountCrossChainMessage.scala
  sdk/src/main/scala/io/horizen/account/sc2sc/AccountCrossChainRedeemMessage.scala
  sdk/src/main/scala/io/horizen/account/state/events/AddCrossChainMessage.scala
  sdk/src/main/scala/io/horizen/utils/Constants.scala
  sdk/src/test/java/io/horizen/cryptolibprovider/implementations/Sc2scImplZendooTest.java
  sdk/src/test/java/io/horizen/sc2sc/CrossChainMessageSemanticValidatorTest.java
  sdk/src/test/java/io/horizen/sc2sc/CrossChainMessageTest.java
  sdk/src/test/java/io/horizen/sc2sc/CrossChainRedeemMessageSemanticValidatorTest.java
  sdk/src/test/java/io/horizen/utxo/box/CrossChainRedeemMessageBoxSerializerTest.java
  sdk/src/test/java/io/horizen/utxo/box/data/CrossChainRedeemMessageBoxDataSerializerTest.java
  sdk/src/test/scala/io/horizen/account/fixtures/AccountCrossChainMessageFixture.scala
  sdk/src/test/scala/io/horizen/account/sc2sc/AbstractCrossChainMessageProcessorTest.scala
  sdk/src/test/scala/io/horizen/account/sc2sc/AbstractCrossChainRedeemMessageProcessorTest.scala
  sdk/src/test/scala/io/horizen/account/state/AccountStateViewTest.scala
  sdk/src/test/scala/io/horizen/api/http/route/Sc2ScApiRouteTest.scala
  sdk/src/test/scala/io/horizen/crosschain/CrossChainMessageMerkleTreeTest.scala
  sdk/src/test/scala/io/horizen/utxo/fixtures/BoxFixture.scala
Labels: 0.3.0

#831 Seeder nodes - St/sdk 1090
  qa/SidechainTestFramework/sc_boostrap_info.py
  qa/SidechainTestFramework/scutil.py
  qa/resources/template.conf
  qa/run_sc_tests.sh
  qa/sc_evm_seedernode.py
  qa/sc_seedernode.py
  sdk/src/main/java/io/horizen/account/api/rpc/service/NotAllowedOnSeederNode.java
  sdk/src/main/java/io/horizen/account/api/rpc/service/RpcService.java
  sdk/src/main/scala/io/horizen/AbstractSidechainApp.scala
  sdk/src/main/scala/io/horizen/NodeViewHolderForSeederNode.scala
  sdk/src/main/scala/io/horizen/SidechainSettings.scala
  sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala
  sdk/src/main/scala/io/horizen/account/AccountSidechainNodeViewHolder.scala
  sdk/src/main/scala/io/horizen/account/api/http/route/AccountBlockApiRoute.scala
  sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala
  sdk/src/main/scala/io/horizen/account/api/http/route/AccountWalletApiRoute.scala
  sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
  sdk/src/main/scala/io/horizen/api/http/route/BlockBaseApiRoute.scala
  sdk/src/main/scala/io/horizen/api/http/route/DisableApiRoute.scala
  sdk/src/main/scala/io/horizen/api/http/route/SidechainRejectionApiRoute.scala
  sdk/src/main/scala/io/horizen/api/http/route/SidechainSubmitterApiRoute.scala
  sdk/src/main/scala/io/horizen/api/http/route/TransactionBaseApiRoute.scala
  sdk/src/main/scala/io/horizen/api/http/route/WalletBaseApiRoute.scala
  sdk/src/main/scala/io/horizen/params/MainNetParams.scala
  sdk/src/main/scala/io/horizen/params/NetworkParams.scala
  sdk/src/main/scala/io/horizen/params/RegTestParams.scala
  sdk/src/main/scala/io/horizen/params/TestNetParams.scala
  sdk/src/main/scala/io/horizen/utxo/SidechainNodeViewHolder.scala
  sdk/src/main/scala/io/horizen/utxo/api/http/route/SidechainBlockApiRoute.scala
  sdk/src/main/scala/io/horizen/utxo/api/http/route/SidechainCswApiRoute.scala
  sdk/src/main/scala/io/horizen/utxo/api/http/route/SidechainTransactionApiRoute.scala
  sdk/src/main/scala/io/horizen/utxo/api/http/route/SidechainWalletApiRoute.scala
  sdk/src/test/java/io/horizen/utils/BytesUtilsTest.java
  sdk/src/test/scala/io/horizen/account/api/http/route/AccountSidechainApiRouteTest.scala
  sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceForSeederTest.scala
  sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala
  tools/sctool/src/main/java/io/horizen/ScBootstrappingToolCommandProcessor.java
Labels: 0.2.0

#861 SDK-1243 - upgrade eth-abi to the latest package
  qa/SidechainTestFramework/account/ac_use_smart_contract.py
  qa/SidechainTestFramework/account/requirements.txt
Labels: 0.2.0

#858 SDK-1207 - App version in node info API
  examples/account/evmapp/src/main/java/io/horizen/examples/EvmAppModule.java
  examples/utxo/simpleapp/src/main/java/io/horizen/examples/SimpleAppModule.java
  sdk/src/main/scala/io/horizen/account/AccountAppModule.scala
  sdk/src/main/scala/io/horizen/account/AccountSidechainApp.scala
  sdk/src/main/scala/io/horizen/api/http/route/SidechainNodeApiRoute.scala
  sdk/src/main/scala/io/horizen/utxo/SidechainApp.scala
  sdk/src/main/scala/io/horizen/utxo/SidechainAppModule.scala
Labels: EON 0.2.0

#840 SDK-1150 - eth_feeHistory pending block tag fix
  qa/run_sc_tests.sh
  qa/sc_evm_feeHistory.py
  sdk/src/main/scala/io/horizen/account/api/rpc/service/EthService.scala
  sdk/src/test/scala/io/horizen/account/api/rpc/service/EthServiceTest.scala
Labels: EON 0.2.0

#867 St/sdk 1242
  qa/SidechainTestFramework/secure_enclave_http_api_server.py
  qa/sc_evm_seedernode.py
  qa/sc_seedernode.py
  sdk/src/main/scala/io/horizen/SidechainSettings.scala
  sdk/src/main/scala/io/horizen/api/http/route/SidechainSubmitterApiRoute.scala
Labels: EON 0.2.0
