Repository HorizenOfficial/Sidechains-SDK, pull requests merged in 2023-07, with the labels that each got.

#860 SDK 809 - NCC Audit suggestion: generateNextSecret
  sdk/src/main/scala/io/horizen/storage/SidechainSecretStorage.scala
  sdk/src/main/scala/io/horizen/wallet/AbstractWallet.scala
  sdk/src/test/scala/io/horizen/account/wallet/AccountWalletTest.scala
  sdk/src/test/scala/io/horizen/integration/storage/SidechainSecretStorageTest.scala
Labels: EON 0.2.0

#882 SDK-1295 - Content-Type HTTP header fix in SecureEnclaveApiClient
  qa/SidechainTestFramework/secure_enclave_http_api_server.py
  sdk/src/main/scala/io/horizen/api/http/client/SecureEnclaveApiClient.scala
  sdk/src/test/scala/io/horizen/api/http/client/SecureEnclaveApiClientTest.scala
Labels: EON 0.2.0

#878 SDK-1255 - default gas limit for key rotation tx increased
  qa/SidechainTestFramework/account/httpCalls/transaction/createKeyRotationTransaction.py
  qa/sc_evm_cert_key_rotation.py
  sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala
Labels: EON 0.2.0

#883 SDK-1253 - sdk pom.xml updated to generate javadoc including scala files
  sdk/pom.xml
Labels: EON 0.3.0

#884 As/zendao optimization
  qa/sc_evm_mc_addr_ownership.py
  qa/sc_evm_mc_addr_ownership_perf_test.py
  sdk/src/main/scala/io/horizen/account/api/http/route/AccountTransactionApiRoute.scala
  sdk/src/main/scala/io/horizen/account/state/McAddrOwnershipMsgProcessor.scala
  sdk/src/test/scala/io/horizen/account/state/McAddrOwnershipMsgProcessorTest.scala
Labels: EON 0.3.0

#857 SDK-1032 - SyncTracker.statuses maps fixes - DO NOT MERGE
  sdk/pom.xml
  sdk/src/main/scala/io/horizen/api/http/route/SidechainNodeApiRoute.scala
Labels: DO NOT MERGE, EON 0.3.0
